//
//  VPNConfigGenerator.swift
//  SOCKS5Server
//
//  Created by SOCKS5 Team
//

import Foundation

/// Generates VPN configuration files for use with the TCP forwarder
/// Supports OpenVPN and WireGuard configuration parsing and generation
class VPNConfigGenerator {
    
    // MARK: - Configuration Types
    
    enum VPNType: String, CaseIterable, Identifiable {
        case openVPN = "OpenVPN"
        case wireGuard = "WireGuard"
        
        var id: String { rawValue }
        
        var fileExtension: String {
            switch self {
            case .openVPN: return "ovpn"
            case .wireGuard: return "conf"
            }
        }
    }
    
    struct VPNEndpoint {
        var host: String
        var port: Int
        var originalConfig: String?
    }
    
    // MARK: - OpenVPN Configuration
    
    /// Parses an OpenVPN config file and extracts the endpoint
    static func parseOpenVPNConfig(_ config: String) -> VPNEndpoint? {
        // Look for "remote <host> <port>" line
        let lines = config.components(separatedBy: .newlines)
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.lowercased().hasPrefix("remote ") {
                let parts = trimmed.split(separator: " ")
                if parts.count >= 3 {
                    let host = String(parts[1])
                    if let port = Int(parts[2]) {
                        return VPNEndpoint(host: host, port: port, originalConfig: config)
                    }
                } else if parts.count == 2 {
                    // Default port 1194
                    return VPNEndpoint(host: String(parts[1]), port: 1194, originalConfig: config)
                }
            }
        }
        
        return nil
    }
    
    /// Generates a modified OpenVPN config pointing to the local TCP forwarder
    static func generateOpenVPNConfig(
        originalConfig: String,
        localHost: String,
        localPort: Int
    ) -> String {
        var lines = originalConfig.components(separatedBy: .newlines)
        var modifiedLines: [String] = []
        var foundRemote = false
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            
            // Replace the remote line
            if trimmed.lowercased().hasPrefix("remote ") && !foundRemote {
                modifiedLines.append("remote \(localHost) \(localPort)")
                modifiedLines.append("# Original: \(line)")
                foundRemote = true
                continue
            }
            
            // Remove or comment out redirect-gateway if it might cause issues
            if trimmed.lowercased().hasPrefix("redirect-gateway") {
                modifiedLines.append("# Commented out for proxy: \(line)")
                continue
            }
            
            modifiedLines.append(line)
        }
        
        // Add helpful comments at the top
        var result = [
            "# Modified OpenVPN config for use with SOCKS5 Server TCP Forwarder",
            "# Local endpoint: \(localHost):\(localPort)",
            "# Generated by SOCKS5 Server App",
            "",
        ]
        result.append(contentsOf: modifiedLines)
        
        // Add recommended settings for proxy mode
        if !originalConfig.lowercased().contains("pull-filter") {
            result.append("")
            result.append("# Recommended settings for proxy mode:")
            result.append("pull-filter ignore \"redirect-gateway def1 bypass-dhcp\"")
            result.append("redirect-gateway local def1 bypass-dhcp")
        }
        
        return result.joined(separator: "\n")
    }
    
    /// Generates a basic OpenVPN config template
    static func generateOpenVPNTemplate(
        localHost: String,
        localPort: Int,
        remoteHost: String,
        remotePort: Int
    ) -> String {
        return """
        # OpenVPN Configuration
        # This config connects through SOCKS5 Server TCP Forwarder
        # Local forwarder: \(localHost):\(localPort)
        # Remote VPN: \(remoteHost):\(remotePort)
        
        client
        dev tun
        proto tcp
        remote \(localHost) \(localPort)
        resolv-retry infinite
        nobind
        persist-key
        persist-tun
        
        # TLS/Security settings (adjust as needed for your VPN provider)
        remote-cert-tls server
        cipher AES-256-GCM
        auth SHA256
        
        # For proxy mode
        pull-filter ignore "redirect-gateway def1 bypass-dhcp"
        redirect-gateway local def1 bypass-dhcp
        
        # Add your CA certificate below
        # <ca>
        # -----BEGIN CERTIFICATE-----
        # Your CA certificate here
        # -----END CERTIFICATE-----
        # </ca>
        
        # Add your authentication credentials if needed
        # auth-user-pass
        """
    }
    
    // MARK: - WireGuard Configuration
    
    /// Parses a WireGuard config file and extracts the endpoint
    static func parseWireGuardConfig(_ config: String) -> VPNEndpoint? {
        let lines = config.components(separatedBy: .newlines)
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.lowercased().hasPrefix("endpoint") {
                // Format: Endpoint = host:port
                if let equalIndex = trimmed.firstIndex(of: "=") {
                    let value = String(trimmed[trimmed.index(after: equalIndex)...])
                        .trimmingCharacters(in: .whitespaces)
                    
                    // Parse host:port
                    if let colonIndex = value.lastIndex(of: ":") {
                        let host = String(value[..<colonIndex])
                        if let port = Int(value[value.index(after: colonIndex)...]) {
                            return VPNEndpoint(host: host, port: port, originalConfig: config)
                        }
                    }
                }
            }
        }
        
        return nil
    }
    
    /// Generates a modified WireGuard config pointing to the local TCP forwarder
    /// Note: WireGuard uses UDP, so this requires wrapping with something like wstunnel
    static func generateWireGuardConfig(
        originalConfig: String,
        localHost: String,
        localPort: Int,
        note: String = ""
    ) -> String {
        var lines = originalConfig.components(separatedBy: .newlines)
        var modifiedLines: [String] = []
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            
            // Replace the Endpoint line
            if trimmed.lowercased().hasPrefix("endpoint") {
                modifiedLines.append("Endpoint = \(localHost):\(localPort)")
                modifiedLines.append("# Original: \(line)")
                continue
            }
            
            modifiedLines.append(line)
        }
        
        // Add helpful comments at the top
        var result = [
            "# Modified WireGuard config for use with SOCKS5 Server TCP Forwarder",
            "# Local endpoint: \(localHost):\(localPort)",
            "# NOTE: WireGuard uses UDP. You need to wrap it with wstunnel or similar",
            "# for TCP tunneling to work properly.",
            "# Generated by SOCKS5 Server App",
        ]
        
        if !note.isEmpty {
            result.append("# \(note)")
        }
        
        result.append("")
        result.append(contentsOf: modifiedLines)
        
        return result.joined(separator: "\n")
    }
    
    /// Generates a basic WireGuard config template
    static func generateWireGuardTemplate(
        localHost: String,
        localPort: Int,
        remoteHost: String,
        remotePort: Int
    ) -> String {
        return """
        # WireGuard Configuration
        # This config connects through SOCKS5 Server TCP Forwarder
        # Local forwarder: \(localHost):\(localPort)
        # Remote VPN: \(remoteHost):\(remotePort)
        #
        # IMPORTANT: WireGuard uses UDP natively. To use with TCP forwarding,
        # you need to wrap the connection with wstunnel or a similar tool
        # on both ends (iPhone and VPN server).
        
        [Interface]
        # Your private key (generate with: wg genkey)
        PrivateKey = YOUR_PRIVATE_KEY_HERE
        # Your VPN IP address
        Address = 10.0.0.2/24
        # DNS server (optional)
        DNS = 1.1.1.1
        
        [Peer]
        # Server's public key
        PublicKey = SERVER_PUBLIC_KEY_HERE
        # Traffic to route through VPN
        AllowedIPs = 0.0.0.0/0
        # Local forwarder endpoint (instead of direct server)
        Endpoint = \(localHost):\(localPort)
        # Keep connection alive
        PersistentKeepalive = 25
        """
    }
    
    // MARK: - Proxy Auto-Config (PAC)
    
    /// Generates a PAC file for the SOCKS5 proxy
    static func generatePACFile(proxyHost: String, proxyPort: Int) -> String {
        return """
        // Proxy Auto-Configuration (PAC) File
        // Generated by SOCKS5 Server App
        // SOCKS5 Proxy: \(proxyHost):\(proxyPort)
        
        function FindProxyForURL(url, host) {
            // Don't proxy local addresses
            if (isPlainHostName(host) ||
                shExpMatch(host, "*.local") ||
                isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
                isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
                isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0") ||
                isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0")) {
                return "DIRECT";
            }
            
            // Use SOCKS5 proxy for everything else
            return "SOCKS5 \(proxyHost):\(proxyPort); SOCKS \(proxyHost):\(proxyPort); DIRECT";
        }
        """
    }
    
    // MARK: - Simple Proxy Config
    
    /// Generates a simple text configuration for the proxy
    static func generateSimpleProxyConfig(
        proxyHost: String,
        proxyPort: Int,
        forwarderHost: String? = nil,
        forwarderPort: Int? = nil,
        remoteVPNHost: String? = nil,
        remoteVPNPort: Int? = nil
    ) -> String {
        var config = """
        ============================================
        SOCKS5 Server Configuration
        ============================================
        
        SOCKS5 PROXY SETTINGS
        ---------------------
        Host: \(proxyHost)
        Port: \(proxyPort)
        Type: SOCKS5
        Authentication: None
        
        Use these settings in:
        - Browser proxy settings
        - Router SOCKS5 proxy configuration
        - Any app that supports SOCKS5 proxy
        
        """
        
        if let fHost = forwarderHost, let fPort = forwarderPort,
           let rHost = remoteVPNHost, let rPort = remoteVPNPort {
            config += """
            
            TCP FORWARDER SETTINGS
            ----------------------
            Local Listen: \(fHost):\(fPort)
            Remote Forward: \(rHost):\(rPort)
            
            This forwards TCP connections from your PC to the VPN server.
            Configure your VPN client to connect to \(fHost):\(fPort)
            instead of \(rHost):\(rPort)
            
            """
        }
        
        config += """
        
        ============================================
        Generated by SOCKS5 Server App
        ============================================
        """
        
        return config
    }
}
